<#$t = '[DllImport("user32.dll")] public static extern bool ShowWindow(int handle, int state);'
add-type -name win -member $t -namespace native
[native.win]::ShowWindow(([System.Diagnostics.Process]::GetCurrentProcess() | Get-Process).MainWindowHandle, 0)
#>

#Generated Form Function
function GenerateForm {

########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 8/25/2016 2:47 PM
# Generated By: asulik
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

### Check to see if Physical or Virtual and only load the forms needed for either
$isThisVirtual = (gwmi -q "select * from win32_computersystem").Manufacturer -match "vmware"
if (($isThisVirtual)){
    $VMPanel = New-Object System.Windows.Forms.Panel
    if (!(test-path HKLM:\SOFTWARE\CSC-SICK)){
        New-Item HKLM:\SOFTWARE\CSC-Sick -ItemType Directory
    }
} else {
    $PhysicalPanel= New-Object System.Windows.Forms.Panel
}

$RegRoot = "HKLM:\Software\CSC-Sick\"



#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$WarrentyExpirationTextBox = New-Object System.Windows.Forms.TextBox
$WarrentyExpirationLabel = New-Object System.Windows.Forms.Label
$CurrentUserTextBox = New-Object System.Windows.Forms.TextBox
$CurrentUserLabel = New-Object System.Windows.Forms.Label
$TechBadgeTextBox = New-Object System.Windows.Forms.TextBox
$TechBadgeLabel = New-Object System.Windows.Forms.Label
$CancelButton = New-Object System.Windows.Forms.Button
$SubmitButton = New-Object System.Windows.Forms.Button
$BuilddatetimeTextBox = New-Object System.Windows.Forms.TextBox
$BuildDateLabel = New-Object System.Windows.Forms.Label
$TabContainer = New-Object System.Windows.Forms.TabControl
$ValidationTab = New-Object System.Windows.Forms.TabPage
$SIEMALETextBox = New-Object System.Windows.Forms.TextBox
$SEPLabel = New-Object System.Windows.Forms.Label
$LanDeskLabel = New-Object System.Windows.Forms.Label
$SEPTextBox = New-Object System.Windows.Forms.TextBox
$LanDeskTextBox = New-Object System.Windows.Forms.TextBox
$BuildAdminTextBox = New-Object System.Windows.Forms.TextBox
$BuildAdminLabel = New-Object System.Windows.Forms.Label
$WUInstallTextBox = New-Object System.Windows.Forms.TextBox
$RSATextBox = New-Object System.Windows.Forms.TextBox
$WUInstallLabel = New-Object System.Windows.Forms.Label
$ADOUTextBox = New-Object System.Windows.Forms.TextBox
$ServerActivationLabel = New-Object System.Windows.Forms.Label
$ServerActivationTextBox = New-Object System.Windows.Forms.TextBox
$ADOULabel = New-Object System.Windows.Forms.Label
$SEIMALEVersionLabel = New-Object System.Windows.Forms.Label
$RSALabel = New-Object System.Windows.Forms.Label
$ServerInfoInputTab = New-Object System.Windows.Forms.TabPage
$SanAttachedComboBox = New-Object System.Windows.Forms.ComboBox
$SanAttachedLabel = New-Object System.Windows.Forms.Label
$CostCenterTextBox = New-Object System.Windows.Forms.TextBox
$CostCenterLabel = New-Object System.Windows.Forms.Label
$ServerFunctionComboBox = New-Object System.Windows.Forms.ComboBox
$ServerFunctionLabel = New-Object System.Windows.Forms.Label
$PrimaryFunctionTextBox = New-Object System.Windows.Forms.TextBox
$PrimaryFunctionLabel = New-Object System.Windows.Forms.Label
$script:AssetTagTextBoxVirtual = New-Object System.Windows.Forms.TextBox
$AssetTagLabelVirtual = New-Object System.Windows.Forms.Label
$VmwareToolsTextBox = New-Object System.Windows.Forms.TextBox
$VmwareToolsLabel = New-Object System.Windows.Forms.Label
$ClusterTextBox = New-Object System.Windows.Forms.TextBox
$ClusterLabel = New-Object System.Windows.Forms.Label
$DataCenterTextBox = New-Object System.Windows.Forms.TextBox
$DataCenterLabel = New-Object System.Windows.Forms.Label
$StateComboBox = New-Object System.Windows.Forms.ComboBox
$AssetTagTextBoxPhysical = New-Object System.Windows.Forms.TextBox
$AssetTagLabelPhysical = New-Object System.Windows.Forms.Label
$ShelfTextBox = New-Object System.Windows.Forms.TextBox
$ShelfLabel = New-Object System.Windows.Forms.Label
$RackTextBox = New-Object System.Windows.Forms.TextBox
$RackLabel = New-Object System.Windows.Forms.Label
$FloorTextBox = New-Object System.Windows.Forms.TextBox
$FloorLabel = New-Object System.Windows.Forms.Label
$StateLabel = New-Object System.Windows.Forms.Label
$CityTextBox = New-Object System.Windows.Forms.TextBox
$CityLabel = New-Object System.Windows.Forms.Label
$StreetLabel = New-Object System.Windows.Forms.Label
$StreetTextBox = New-Object System.Windows.Forms.TextBox
$ServerHistoryTab = New-Object System.Windows.Forms.TabPage
$vScrollBar1 = New-Object System.Windows.Forms.VScrollBar
$dataGridView1 = New-Object System.Windows.Forms.DataGridView
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$CancelButton_OnClick= 
{

}

$handler_BuildAdminLabel_Click= 
{
#TODO: Place custom script here

}

$handler_SEPTextBox_TextChanged= 
{
#TODO: Place custom script here
}

$handler_ADOULabel_Click= 
{
#TODO: Place custom script here

}

$handler_label6_Click= 
{
#TODO: Place custom script here

}

$SubmitButton_OnClick= 
{
    if ($WarrentyExpirationTextBox.Text.Length -gt 0){
        if ($WarrentyExpirationTextBox.Text -notmatch '^((((0[13578])|(1[02]))[\/]?(([0-2][0-9])|(3[01])))|(((0[469])|(11))[\/]?(([0-2][0-9])|(30)))|(02[\/]?[0-2][0-9]))[\/]?\d{4}$') {
            $wshell = New-Object -ComObject Wscript.Shell
            $wshell.Popup("Warrenty Date must be formated as such: `n01/05/2015`nMM/DD/YYYY",0,"Warrenty Date ERROR",0x0 + 16)
            $wrongDate = $true
        }
    }

    if (!($wrongDate)) {
        $wshell = New-Object -ComObject Wscript.Shell
        $YesOrNo = $wshell.Popup("Are you sure you'd like to exit `nand save the entered data?",0,"Are You Sure you'd like to quit?",0x4 + 32)
        if ($YesOrNo -eq 7){
        
        } elseif ($YesOrNo -eq 6) {
            if ((Get-ItemProperty -Path $RegRoot | select -ExpandProperty BuildAdmin).length -le 0) {Set-ItemProperty -Path $RegRoot -Name BuildAdmin -Value $BuildAdminTextBox.Text}

            if ($isThisVirtual){Set-ItemProperty -Path $RegRoot -Name AssetTag -Value $script:AssetTagTextBoxVirtual.Text} else {}
            Set-ItemProperty -Path $RegRoot -Name City -Value $CityTextBox.Text
            Set-ItemProperty -Path $RegRoot -Name Cluster -Value $ClusterTextBox.Text
            Set-ItemProperty -Path $RegRoot -Name CostCenter -Value $CostCenterTextBox.text
            Set-ItemProperty -Path $RegRoot -Name DataCenter -Value $DataCenterTextBox.Text
            Set-ItemProperty -Path $RegRoot -Name Floor -Value $FloorTextBox.Text
            Set-ItemProperty -Path $RegRoot -Name LanDeskVersion -Value $LanDeskTextBox.Text
            Set-ItemProperty -Path $RegRoot -Name PrimaryFunction -Value $PrimaryFunctionTextBox.Text -Type MultiString
            Set-ItemProperty -Path $RegRoot -Name Rack -Value $RackTextBox.Text
            Set-ItemProperty -Path $RegRoot -Name RSAVersion -Value $RSATextBox.Text
            Set-ItemProperty -Path $RegRoot -Name SanAttached -Value $SanAttachedComboBox.Text
            Set-ItemProperty -Path $RegRoot -Name SEPVersion -Value $SEPTextBox.Text
            Set-ItemProperty -Path $RegRoot -Name ServerActivation -Value $ServerActivationTextBox.Text
            Set-ItemProperty -Path $RegRoot -Name ServerFunction -Value $ServerFunctionComboBox.Text
            Set-ItemProperty -Path $RegRoot -Name Shelf -Value $ShelfTextBox.Text
            Set-ItemProperty -Path $RegRoot -Name SIEM/ALEVersion -Value $SIEMALETextBox.Text
            Set-ItemProperty -Path $RegRoot -Name State -Value $StateComboBox.Text
            Set-ItemProperty -Path $RegRoot -Name StreetAddress -Value $StreetTextBox.Text
            Set-ItemProperty -Path $RegRoot -Name VMWareToolsVersion -Value $VmwareToolsTextBox.Text
            Set-ItemProperty -Path $RegRoot -Name WUInstall -Value $WUInstallTextBox.Text
            Set-ItemProperty -Path $RegRoot -Name WarrantyExpiration -Value $WarrentyExpirationTextBox.Text

            [Environment]::Exit(1)
        
        } else {
            $wshell = New-Object -ComObject Wscript.Shell
            $wshell.Popup("Something went horribly wrong. Contact Adam Sulik `nWe are exiting without saving any data",0x0 + 16)
        }
    }

}


$handler_label8_Click= 
{
#TODO: Place custom script here

}

$handler_SEPLabel_Click= 
{
#TODO: Place custom script here

}

$handler_LanDeskLabel_Click= 
{
#TODO: Place custom script here

}

$handler_TabPage:_Click= 
{
#TODO: Place custom script here

}
$handler_ClusterTextBox_TextChanged={
    if ($ClusterTextBox.Text.Length -gt 0){
    $AssetTagTextBoxVirtual.Text = $ClusterTextBox.Text+"\"+$env:computername
    } else {
    $AssetTagTextBoxVirtual.Text = ""
    }

}

$handler_TechBadgeTextBox_TextChanged={
    if ($TechBadgeTextBox.text.length -eq 10){
        $searcher = New-Object Directoryservices.DirectorySearcher
        $searcher.Filter = '(samaccountname='+$env:username+')'
        $badge = ($searcher.FindAll().properties.'msds-cloudextensionattribute18').substring(0,6)
        $pin = ($searcher.FindAll().properties.'msds-cloudextensionattribute18').substring(6,4)
        if (($TechBadgeTextBox.Text -eq ($badge + $pin)) -or ($TechBadgeTextBox.Text -eq ($pin + $badge))){
            $TabContainer.Enabled = $True
            $SubmitButton.Enabled = $True
        } else {
            $wshell = New-Object -ComObject Wscript.Shell
            $wshell.Popup("You entered the wrong PIN please try again.",0x0 + 16)
        }

    }else {
        $TabContainer.Enabled = $False
        $SubmitButton.Enabled = $False
    } 
}


$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$form1.BackColor = [System.Drawing.Color]::FromArgb(255,176,224,230)

$form1.BackgroundImageLayout = 3
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 513
$System_Drawing_Size.Width = 750
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.DoubleBuffered = $True
$form1.ForeColor = [System.Drawing.Color]::FromArgb(255,105,105,105)
$form1.FormBorderStyle = 2
$form1.Name = "form1"
$form1.Text = "S.I.C.K. Server Information Collection and Knowledge Base"

$CurrentUserTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,227,227,227)
$CurrentUserTextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 110
$System_Drawing_Point.Y = 10
$CurrentUserTextBox.Location = $System_Drawing_Point
$CurrentUserTextBox.Name = "CurrentUserTextBox"
$CurrentUserTextBox.ReadOnly = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 150
$CurrentUserTextBox.Size = $System_Drawing_Size
$CurrentUserTextBox.TabIndex = 24
$CurrentUserTextBox.Text = "$env:userdomain\$env:username"

$form1.Controls.Add($CurrentUserTextBox)

$CurrentUserLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$CurrentUserLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 9
$CurrentUserLabel.Location = $System_Drawing_Point
$CurrentUserLabel.Name = "CurrentUserLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 110
$CurrentUserLabel.Size = $System_Drawing_Size
$CurrentUserLabel.TabIndex = 23
$CurrentUserLabel.Text = "Current User"

$form1.Controls.Add($CurrentUserLabel)


$TechBadgeTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,227,227,227)
$TechBadgeTextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 300  #110
$System_Drawing_Point.Y = 40 #40
$TechBadgeTextBox.Location = $System_Drawing_Point
$TechBadgeTextBox.Name = "TechBadgeTextBox"
$TechBadgeTextBox.ReadOnly = $False
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 150
$TechBadgeTextBox.Size = $System_Drawing_Size
$TechBadgeTextBox.TabIndex = 24
$TechBadgeTextBox.PasswordChar = "X"
$TechBadgeTextBox.add_TextChanged($handler_TechBadgeTextBox_TextChanged)
$TechBadgeTextBox.Text = ""

$form1.Controls.Add($TechBadgeTextBox)

$TechBadgeLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$TechBadgeLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 300
$System_Drawing_Point.Y = 20
$TechBadgeLabel.Location = $System_Drawing_Point
$TechBadgeLabel.Name = "TechBadgeLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 150
$TechBadgeLabel.Size = $System_Drawing_Size
$TechBadgeLabel.TabIndex = 23
$TechBadgeLabel.Text = "Tech Badge and Pin"

$form1.Controls.Add($TechBadgeLabel)


$CancelButton.BackColor = [System.Drawing.Color]::FromArgb(0,255,255,255)

$CancelButton.DataBindings.DefaultDataSourceUpdateMode = 0
$CancelButton.Font = New-Object System.Drawing.Font("Calibri",12,0,3,0)
$CancelButton.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 19
$System_Drawing_Point.Y = 472
$CancelButton.Location = $System_Drawing_Point
$CancelButton.Name = "CancelButton"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 38
$System_Drawing_Size.Width = 106
$CancelButton.Size = $System_Drawing_Size
$CancelButton.TabIndex = 22
$CancelButton.Text = "CANCEL"
$CancelButton.UseVisualStyleBackColor = $False
$CancelButton.add_Click($CancelButton_OnClick)

$form1.Controls.Add($CancelButton)

$SubmitButton.BackColor = [System.Drawing.Color]::FromArgb(0,255,255,255)

$SubmitButton.DataBindings.DefaultDataSourceUpdateMode = 0
$SubmitButton.Font = New-Object System.Drawing.Font("Calibri",12,0,3,0)
$SubmitButton.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 624
$System_Drawing_Point.Y = 472
$SubmitButton.Location = $System_Drawing_Point
$SubmitButton.Name = "SubmitButton"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 38
$System_Drawing_Size.Width = 106
$SubmitButton.Size = $System_Drawing_Size
$SubmitButton.TabIndex = 21
$SubmitButton.Text = "SUBMIT"
$SubmitButton.UseVisualStyleBackColor = $False
$SubmitButton.add_Click($SubmitButton_OnClick)
$SubmitButton.Enabled = $False

$form1.Controls.Add($SubmitButton)

$BuilddatetimeTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,227,227,227)
$BuilddatetimeTextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 624
$System_Drawing_Point.Y = 12
$BuilddatetimeTextBox.Location = $System_Drawing_Point
$BuilddatetimeTextBox.Name = "BuilddatetimeTextBox"
$BuilddatetimeTextBox.ReadOnly = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$BuilddatetimeTextBox.Size = $System_Drawing_Size
$BuilddatetimeTextBox.TabIndex = 20

$form1.Controls.Add($BuilddatetimeTextBox)

$BuildDateLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$BuildDateLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,0)
$BuildDateLabel.ForeColor = [System.Drawing.Color]::FromArgb(255,105,105,105)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 528
$System_Drawing_Point.Y = 9
$BuildDateLabel.Location = $System_Drawing_Point
$BuildDateLabel.Name = "BuildDateLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$BuildDateLabel.Size = $System_Drawing_Size
$BuildDateLabel.TabIndex = 19
$BuildDateLabel.Text = "Build Date"

$form1.Controls.Add($BuildDateLabel)

$TabContainer.Appearance = 2
$TabContainer.Cursor = [System.Windows.Forms.Cursors]::Arrow
$TabContainer.DataBindings.DefaultDataSourceUpdateMode = 0
$TabContainer.Font = New-Object System.Drawing.Font("Calibri",10,1,3,1)
$TabContainer.HotTrack = $True
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 21
$System_Drawing_Point.Y = 87
$TabContainer.Location = $System_Drawing_Point
$TabContainer.Name = "TabContainer"
$TabContainer.SelectedIndex = 0
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 362
$System_Drawing_Size.Width = 718
$TabContainer.Size = $System_Drawing_Size
$TabContainer.TabIndex = 18
$TabContainer.Enabled = $False

$form1.Controls.Add($TabContainer)

$ValidationTab.BackColor = [System.Drawing.Color]::FromArgb(255,176,224,230)
$ValidationTab.BackgroundImageLayout = 0
$ValidationTab.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 27
$ValidationTab.Location = $System_Drawing_Point
$ValidationTab.Name = "ValidationTab"
$System_Windows_Forms_Padding = New-Object System.Windows.Forms.Padding
$System_Windows_Forms_Padding.All = 3
$System_Windows_Forms_Padding.Bottom = 3
$System_Windows_Forms_Padding.Left = 3
$System_Windows_Forms_Padding.Right = 3
$System_Windows_Forms_Padding.Top = 3
$ValidationTab.Padding = $System_Windows_Forms_Padding
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 331
$System_Drawing_Size.Width = 710
$ValidationTab.Size = $System_Drawing_Size
$ValidationTab.TabIndex = 0
$ValidationTab.Text = "Validation"
$ValidationTab.add_Click($handler_TabPage:_Click)

$TabContainer.Controls.Add($ValidationTab)

$SIEMALETextBox.Font = New-Object System.Drawing.Font("Calibri",12,1,3,0)
$SIEMALETextBox.BackColor = [System.Drawing.Color]::FromArgb(255,227,227,227)
$SIEMALETextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 202
$SIEMALETextBox.Location = $System_Drawing_Point
$SIEMALETextBox.Name = "SIEMALETextBox"
$SIEMALETextBox.ReadOnly = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 150
$SIEMALETextBox.Size = $System_Drawing_Size
$SIEMALETextBox.TabIndex = 4
# Get SEIM Version
foreach ($service in (gwmi -q "select * from Win32_service")){if ($service.pathname -match "Q1WindowsAgentSvc.exe"){$SEIMName = $Service}}

if ($SEIMName -ne $null){
    foreach ($line in (gc (((($seimname.PathName.split("`"") -split "Q1WindowsAgentSvc.exe")[1] -split "bin")[0])+"logs\ALE_System.log"))) {
        if ($line -match "ALE Version") {
            $SIEMALETextBox.Text = $line.split(":")[3]
            if (($line.split(":")[3] -ne "") -or ($line.split(":")[3] -ne $null)){
                $SIEMALETextBox.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
                $SIEMALETextBox.BackColor = [System.Drawing.Color]::FromArgb(255,51,189,61)
            } else {
                    $SIEMALETextBox.Text = "ALE NOT DETECTED"
                    $SIEMALETextBox.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
                    $SIEMALETextBox.BackColor = [System.Drawing.Color]::FromArgb(255,255,0,0)
            }
            break 
        }
    }
} else {
    $SIEMALETextBox.Text = "ALE NOT DETECTED"
    $SIEMALETextBox.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
    $SIEMALETextBox.BackColor = [System.Drawing.Color]::FromArgb(255,255,0,0)
}
#

$ValidationTab.Controls.Add($SIEMALETextBox)

$SEPLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$SEPLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,0)
$SEPLabel.ForeColor = [System.Drawing.Color]::FromArgb(255,105,105,105)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 172
$System_Drawing_Point.Y = 89
$SEPLabel.Location = $System_Drawing_Point
$SEPLabel.Name = "SEPLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$SEPLabel.Size = $System_Drawing_Size
$SEPLabel.TabIndex = 0
$SEPLabel.Text = "SEP Version"
$SEPLabel.add_Click($handler_SEPLabel_Click)

$ValidationTab.Controls.Add($SEPLabel)

$LanDeskLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$LanDeskLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,0)
$LanDeskLabel.ForeColor = [System.Drawing.Color]::FromArgb(255,105,105,105)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 172
$System_Drawing_Point.Y = 135
$LanDeskLabel.Location = $System_Drawing_Point
$LanDeskLabel.Name = "LanDeskLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 157
$LanDeskLabel.Size = $System_Drawing_Size
$LanDeskLabel.TabIndex = 2
$LanDeskLabel.Text = "LanDesk Version"
$LanDeskLabel.add_Click($handler_LanDeskLabel_Click)

$ValidationTab.Controls.Add($LanDeskLabel)

$SEPTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,227,227,227)
$SEPTextBox.Font = New-Object System.Drawing.Font("Calibri",12,1,3,0)
$SEPTextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 172
$System_Drawing_Point.Y = 112
$SEPTextBox.Location = $System_Drawing_Point
$SEPTextBox.Name = "SEPTextBox"
$SEPTextBox.ReadOnly = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 150
$SEPTextBox.Size = $System_Drawing_Size
$SEPTextBox.TabIndex = 1
$SEPTextBox.add_TextChanged($handler_SEPTextBox_TextChanged)
$SEPDirectory = $null
$SEPDirectory = (dir -Recurse 'C:\Program Files (x86)\*\sms.dll').Directory.fullname
if ($SEPDirectory -ne $null){
    $SEPVers = [system.diagnostics.fileversioninfo]::GetVersionInfo("$SEPDirectory\sms.dll").productversion
    if ($SEPVers -eq "12.1.7004.6500"){
        $SEPTextBox.Text =$SEPVers
        $SEPTextBox.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
        $SEPTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,51,189,61)
    } else {
        $SEPTextBox.Text =$SEPVers
        $SEPTextBox.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
        $SEPTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,246,255,101)
    }
} elseif ((dir -Recurse 'C:\Program Files\*\sms.dll').Directory.fullname -ne $null) {
    $SEPVers = [system.diagnostics.fileversioninfo]::GetVersionInfo((dir -Recurse 'C:\Program Files\*\sms.dll').Directory.fullname + "\sms.dll").productversion
    if ($SEPVers -eq "12.1.7004.6500"){
        $SEPTextBox.Text =$SEPVers
        $SEPTextBox.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
        $SEPTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,51,189,61)
    } else {
        $SEPTextBox.Text =$SEPVers
        $SEPTextBox.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
        $SEPTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,246,255,101)
    }
} else {
    $SEPTextBox.Text = "SEP NOT DETECTED"
    $SEPTextBox.ForeColor = [System.Drawing.Color]::FromArgb(255,255,0,0)
    $SEPTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,0,0,0)

}


$ValidationTab.Controls.Add($SEPTextBox)

$LanDeskTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,227,227,227)
$LanDeskTextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 172
$System_Drawing_Point.Y = 158
$LanDeskTextBox.Location = $System_Drawing_Point
$LanDeskTextBox.Name = "LanDeskTextBox"
$LanDeskTextBox.ReadOnly = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 100
$LanDeskTextBox.Size = $System_Drawing_Size
$LanDeskTextBox.TabIndex = 3
$LanDeskTextBox.Font = New-Object System.Drawing.Font("Calibri",12,1,3,0)
$LANDirectory = (dir -Recurse 'C:\Program Files (x86)\*\residentagent.exe').Directory.fullname
if ($LANDirectory -ne $null){
    $LANVers = [system.diagnostics.fileversioninfo]::GetVersionInfo("$LANDirectory\residentagent.exe").productversion
    if ($LANVers -eq "9.0.3.41"){
        $LanDeskTextBox.Text =$LANVers
        $LanDeskTextBox.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
        $LanDeskTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,51,189,61)
    } else {
        $LanDeskTextBox.Text =$LANVers
        $LanDeskTextBox.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
        $LanDeskTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,246,255,101)
    }
} elseif ((dir -Recurse 'C:\Program Files\*\residentagent.exe').Directory.fullname -ne $null) {
    $LANVers = [system.diagnostics.fileversioninfo]::GetVersionInfo((dir -Recurse 'C:\Program Files\*\residentagent.exe').Directory.fullname + "\residentagent.exe").productversion
    if ($LANVers -eq "9.0.3.41"){
        $LanDeskTextBox.Text =$LANVers
        $LanDeskTextBox.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
        $LanDeskTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,51,189,61)
    } else {
        $LanDeskTextBox.Text =$LANVers
        $LanDeskTextBox.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
        $LanDeskTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,246,255,101)
    }
} else {
    $LanDeskTextBox.Text = "LANDESK NOT DETECTED"
    $LanDeskTextBox.ForeColor = [System.Drawing.Color]::FromArgb(255,255,0,0)
    $LanDeskTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,0,0,0)

}



$ValidationTab.Controls.Add($LanDeskTextBox)

$BuildAdminTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,227,227,227)
$BuildAdminTextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 560
$System_Drawing_Point.Y = 24
$BuildAdminTextBox.Location = $System_Drawing_Point
$BuildAdminTextBox.Name = "BuildAdminTextBox"
$BuildAdminTextBox.ReadOnly = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 129
$BuildAdminTextBox.Size = $System_Drawing_Size
$BuildAdminTextBox.TabIndex = 17
#$BuildAdminTextBox.Text = (Get-ItemProperty -path HKLM:\Software\CSC-Sick -Name BuildAdmin).BuildAdmin
if ($BuildAdminTextBox.Text.Length -eq 0){
    $BuildAdminTextBox.Text = $CurrentUserTextBox.Text
}

$ValidationTab.Controls.Add($BuildAdminTextBox)

$BuildAdminLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$BuildAdminLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,0)
$BuildAdminLabel.ForeColor = [System.Drawing.Color]::FromArgb(255,105,105,105)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 454
$System_Drawing_Point.Y = 23
$BuildAdminLabel.Location = $System_Drawing_Point
$BuildAdminLabel.Name = "BuildAdminLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$BuildAdminLabel.Size = $System_Drawing_Size
$BuildAdminLabel.TabIndex = 16
$BuildAdminLabel.Text = "Build Admin"
$BuildAdminLabel.add_Click($handler_BuildAdminLabel_Click)

$ValidationTab.Controls.Add($BuildAdminLabel)

$WUInstallTextBox.Font = New-Object System.Drawing.Font("Calibri",12,1,3,0)
$WUInstallTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,227,227,227)
$WUInstallTextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 172
$System_Drawing_Point.Y = 201
$WUInstallTextBox.Location = $System_Drawing_Point
$WUInstallTextBox.Name = "WUInstallTextBox"
$WUInstallTextBox.ReadOnly = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 220
$WUInstallTextBox.Size = $System_Drawing_Size
$WUInstallTextBox.TabIndex = 13
#Find WU Install Tool
if (test-path C:\bin\WUInstall.exe) {
    $WUInstallTextBox.text = "C:\bin\WUInstall.exe"
    $WUInstallTextBox.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
    $WUInstallTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,51,189,61)
} else {
    $WUInstallTextBox.text = "WUInstall not found in C:\Bin"
    $WUInstallTextBox.ForeColor = [System.Drawing.Color]::FromArgb(255,255,0,0)
    $WUInstallTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
}

$ValidationTab.Controls.Add($WUInstallTextBox)

$RSATextBox.BackColor = [System.Drawing.Color]::FromArgb(255,227,227,227)
$RSATextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 161
$RSATextBox.Location = $System_Drawing_Point
$RSATextBox.Name = "RSATextBox"
$RSATextBox.ReadOnly = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 120
$RSATextBox.Size = $System_Drawing_Size
$RSATextBox.TabIndex = 5
$RSATextBox.Font = New-Object System.Drawing.Font("Calibri",12,1,3,0)
If (Test-path 'HKLM:\Software\RSA\RSA Authentication Agent\CurrentVersion'){
    $RSATextBox.Text = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\RSA\RSA Authentication Agent\CurrentVersion' -Name ProductVersion).productversion
    $RSATextBox.Font = New-Object System.Drawing.Font("Calibri",12,1,3,0)
    $RSATextBox.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
    $RSATextBox.BackColor = [System.Drawing.Color]::FromArgb(255,51,189,61)
} else {
    $RSATextBox.Text = "NOT INSTALLED"
    $RSATextBox.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
    $RSATextBox.BackColor = [System.Drawing.Color]::FromArgb(255,255,0,0)
}

$ValidationTab.Controls.Add($RSATextBox)

$WUInstallLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$WUInstallLabel.FlatStyle = 3
$WUInstallLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,0)
$WUInstallLabel.ForeColor = [System.Drawing.Color]::FromArgb(255,105,105,105)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 172
$System_Drawing_Point.Y = 185
$WUInstallLabel.Location = $System_Drawing_Point
$WUInstallLabel.Name = "WUInstallLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 26
$System_Drawing_Size.Width = 143
$WUInstallLabel.Size = $System_Drawing_Size
$WUInstallLabel.TabIndex = 12
$WUInstallLabel.Text = "WUInstall"

$ValidationTab.Controls.Add($WUInstallLabel)

$ADOUTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,227,227,227)
$ADOUTextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 3
$System_Drawing_Point.Y = 26
$ADOUTextBox.Location = $System_Drawing_Point
$ADOUTextBox.Multiline = $True
$ADOUTextBox.Name = "ADOUTextBox"
$ADOUTextBox.ReadOnly = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 51
$System_Drawing_Size.Width = 264
$ADOUTextBox.Size = $System_Drawing_Size
$ADOUTextBox.TabIndex = 6
$ADOUTextBox.Text = (get-adcomputer $env:computername -properties Distinguishedname).Distinguishedname

$ValidationTab.Controls.Add($ADOUTextBox)

$ServerActivationLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$ServerActivationLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,0)
$ServerActivationLabel.ForeColor = [System.Drawing.Color]::FromArgb(255,105,105,105)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 3
$System_Drawing_Point.Y = 90
$ServerActivationLabel.Location = $System_Drawing_Point
$ServerActivationLabel.Name = "ServerActivationLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 19
$System_Drawing_Size.Width = 143
$ServerActivationLabel.Size = $System_Drawing_Size
$ServerActivationLabel.TabIndex = 11
$ServerActivationLabel.Text = "Server Activation"
$ServerActivationLabel.add_Click($handler_label6_Click)

$ValidationTab.Controls.Add($ServerActivationLabel)

$ServerActivationTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,227,227,227)
$ServerActivationTextBox.Font = New-Object System.Drawing.Font("Calibri",12,1,3,0)
$ServerActivationTextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 112
$ServerActivationTextBox.Location = $System_Drawing_Point
$ServerActivationTextBox.Name = "ServerActivationTextBox"
$ServerActivationTextBox.ReadOnly = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 131
$ServerActivationTextBox.Size = $System_Drawing_Size
$ServerActivationTextBox.TabIndex = 7
### Verifiy if windows is activated
$SoftwareLicensingProduct = (Get-CimInstance SoftwareLicensingProduct | where licensestatus -eq 1)
if ($SoftwareLicensingProduct.name.count -gt 0){
    $ServerActivationTextBox.Text = "ACTIVATED"
    $ServerActivationTextBox.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
    $ServerActivationTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,51,189,61)
} else {
    $ServerActivationTextBox.Text = "NOT-ACTIVATED"
    $ServerActivationTextBox.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
    $ServerActivationTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,255,0,0)
}

###

$ValidationTab.Controls.Add($ServerActivationTextBox)

$ADOULabel.DataBindings.DefaultDataSourceUpdateMode = 0
$ADOULabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,0)
$ADOULabel.ForeColor = [System.Drawing.Color]::FromArgb(255,105,105,105)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 3
$System_Drawing_Point.Y = 10
$ADOULabel.Location = $System_Drawing_Point
$ADOULabel.Name = "ADOULabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 131
$ADOULabel.Size = $System_Drawing_Size
$ADOULabel.TabIndex = 10
$ADOULabel.Text = "AD OU Location"
$ADOULabel.add_Click($handler_ADOULabel_Click)

$ValidationTab.Controls.Add($ADOULabel)

$SEIMALEVersionLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$SEIMALEVersionLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,0)
$SEIMALEVersionLabel.ForeColor = [System.Drawing.Color]::FromArgb(255,105,105,105)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 184
$SEIMALEVersionLabel.Location = $System_Drawing_Point
$SEIMALEVersionLabel.Name = "SEIMALEVersionLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 15
$System_Drawing_Size.Width = 131
$SEIMALEVersionLabel.Size = $System_Drawing_Size
$SEIMALEVersionLabel.TabIndex = 8
$SEIMALEVersionLabel.Text = "SEIM/ALE Version"

$ValidationTab.Controls.Add($SEIMALEVersionLabel)

$RSALabel.DataBindings.DefaultDataSourceUpdateMode = 0
$RSALabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,0)
$RSALabel.ForeColor = [System.Drawing.Color]::FromArgb(255,105,105,105)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 135
$RSALabel.Location = $System_Drawing_Point
$RSALabel.Name = "RSALabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 117
$RSALabel.Size = $System_Drawing_Size
$RSALabel.TabIndex = 9
$RSALabel.Text = "RSA Version"

$ValidationTab.Controls.Add($RSALabel)


$ServerInfoInputTab.BackColor = [System.Drawing.Color]::FromArgb(255,176,224,230)
$ServerInfoInputTab.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 27
$ServerInfoInputTab.Location = $System_Drawing_Point
$ServerInfoInputTab.Name = "ServerInfoInputTab"
$System_Windows_Forms_Padding = New-Object System.Windows.Forms.Padding
$System_Windows_Forms_Padding.All = 3
$System_Windows_Forms_Padding.Bottom = 3
$System_Windows_Forms_Padding.Left = 3
$System_Windows_Forms_Padding.Right = 3
$System_Windows_Forms_Padding.Top = 3
$ServerInfoInputTab.Padding = $System_Windows_Forms_Padding
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 331
$System_Drawing_Size.Width = 710
$ServerInfoInputTab.Size = $System_Drawing_Size
$ServerInfoInputTab.TabIndex = 1
$ServerInfoInputTab.Text = "Server Info Input"

$TabContainer.Controls.Add($ServerInfoInputTab)
$SanAttachedComboBox.DataBindings.DefaultDataSourceUpdateMode = 0
$SanAttachedComboBox.FormattingEnabled = $True
$SanAttachedComboBox.Items.Add("YES")|Out-Null
$SanAttachedComboBox.Items.Add("NO")|Out-Null
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 442
$System_Drawing_Point.Y = 198
$SanAttachedComboBox.Location = $System_Drawing_Point
$SanAttachedComboBox.Name = "SanAttachedComboBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 121
$SanAttachedComboBox.Size = $System_Drawing_Size
$SanAttachedComboBox.TabIndex = 23

$ServerInfoInputTab.Controls.Add($SanAttachedComboBox)

$SanAttachedLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$SanAttachedLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,1)
$SanAttachedLabel.ForeColor = [System.Drawing.Color]::FromArgb(255,105,105,105)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 442
$System_Drawing_Point.Y = 181
$SanAttachedLabel.Location = $System_Drawing_Point
$SanAttachedLabel.Name = "SanAttachedLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 121
$SanAttachedLabel.Size = $System_Drawing_Size
$SanAttachedLabel.TabIndex = 22
$SanAttachedLabel.Text = "SAN Attached?"

$ServerInfoInputTab.Controls.Add($SanAttachedLabel)

$CostCenterTextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 442
$System_Drawing_Point.Y = 159
$CostCenterTextBox.Location = $System_Drawing_Point
$CostCenterTextBox.Name = "CostCenterTextBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 100
$CostCenterTextBox.Size = $System_Drawing_Size
$CostCenterTextBox.TabIndex = 21

$ServerInfoInputTab.Controls.Add($CostCenterTextBox)

$CostCenterLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$CostCenterLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,1)
$CostCenterLabel.ForeColor = [System.Drawing.Color]::FromArgb(255,105,105,105)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 442
$System_Drawing_Point.Y = 142
$CostCenterLabel.Location = $System_Drawing_Point
$CostCenterLabel.Name = "CostCenterLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 108
$CostCenterLabel.Size = $System_Drawing_Size
$CostCenterLabel.TabIndex = 20
$CostCenterLabel.Text = "Cost Center"

$ServerInfoInputTab.Controls.Add($CostCenterLabel)

$ServerFunctionComboBox.DataBindings.DefaultDataSourceUpdateMode = 0
$ServerFunctionComboBox.FormattingEnabled = $True
$ServerFunctionComboBox.Items.Add("Infrastructure")|Out-Null
$ServerFunctionComboBox.Items.Add("Application")|Out-Null
$ServerFunctionComboBox.Items.Add("Database")|Out-Null
$ServerFunctionComboBox.Items.Add("Print server")|Out-Null
$ServerFunctionComboBox.Items.Add("File Server")|Out-Null
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 442
$System_Drawing_Point.Y = 116
$ServerFunctionComboBox.Location = $System_Drawing_Point
$ServerFunctionComboBox.Name = "ServerFunctionComboBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 121
$ServerFunctionComboBox.Size = $System_Drawing_Size
$ServerFunctionComboBox.TabIndex = 19

$ServerInfoInputTab.Controls.Add($ServerFunctionComboBox)

$ServerFunctionLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$ServerFunctionLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,1)
$ServerFunctionLabel.ForeColor = [System.Drawing.Color]::FromArgb(255,105,105,105)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 442
$System_Drawing_Point.Y = 99
$ServerFunctionLabel.Location = $System_Drawing_Point
$ServerFunctionLabel.Name = "ServerFunctionLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 121
$ServerFunctionLabel.Size = $System_Drawing_Size
$ServerFunctionLabel.TabIndex = 18
$ServerFunctionLabel.Text = "Server Function"

$ServerInfoInputTab.Controls.Add($ServerFunctionLabel)

$PrimaryFunctionTextBox.AcceptsReturn = $True
$PrimaryFunctionTextBox.AcceptsTab = $True
$PrimaryFunctionTextBox.AllowDrop = $True
$PrimaryFunctionTextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 442
$System_Drawing_Point.Y = 41
$PrimaryFunctionTextBox.Location = $System_Drawing_Point
$PrimaryFunctionTextBox.Multiline = $True
$PrimaryFunctionTextBox.Name = "PrimaryFunctionTextBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 55
$System_Drawing_Size.Width = 193
$PrimaryFunctionTextBox.Size = $System_Drawing_Size
$PrimaryFunctionTextBox.TabIndex = 17

$ServerInfoInputTab.Controls.Add($PrimaryFunctionTextBox)

$PrimaryFunctionLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$PrimaryFunctionLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,1)
$PrimaryFunctionLabel.ForeColor = [System.Drawing.Color]::FromArgb(255,105,105,105)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 442
$System_Drawing_Point.Y = 15
$PrimaryFunctionLabel.Location = $System_Drawing_Point
$PrimaryFunctionLabel.Name = "PrimaryFunctionLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 147
$PrimaryFunctionLabel.Size = $System_Drawing_Size
$PrimaryFunctionLabel.TabIndex = 16
$PrimaryFunctionLabel.Text = "Primary Function"

$ServerInfoInputTab.Controls.Add($PrimaryFunctionLabel)


$VMPanel.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 3
$System_Drawing_Point.Y = 3
$VMPanel.Location = $System_Drawing_Point
$VMPanel.Name = "VMPanel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 255
$System_Drawing_Size.Width = 407
$VMPanel.Size = $System_Drawing_Size
$VMPanel.TabIndex = 15

$ServerInfoInputTab.Controls.Add($VMPanel)

$script:AssetTagTextBoxVirtual.BackColor = [System.Drawing.Color]::FromArgb(255,227,227,227)
$script:AssetTagTextBoxVirtual.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 189
$script:AssetTagTextBoxVirtual.Location = $System_Drawing_Point
$script:AssetTagTextBoxVirtual.Name = "AssetTagTextBoxVirtual"
$script:AssetTagTextBoxVirtual.ReadOnly = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 200
$script:AssetTagTextBoxVirtual.Size = $System_Drawing_Size
$script:AssetTagTextBoxVirtual.TabIndex = 7

$VMPanel.Controls.Add($script:AssetTagTextBoxVirtual)

$AssetTagLabelVirtual.DataBindings.DefaultDataSourceUpdateMode = 0
$AssetTagLabelVirtual.Font = New-Object System.Drawing.Font("Calibri",12,1,3,1)
$AssetTagLabelVirtual.ForeColor = [System.Drawing.Color]::FromArgb(255,105,105,105)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 171
$AssetTagLabelVirtual.Location = $System_Drawing_Point
$AssetTagLabelVirtual.Name = "AssetTagLabelVirtual"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$AssetTagLabelVirtual.Size = $System_Drawing_Size
$AssetTagLabelVirtual.TabIndex = 6
$AssetTagLabelVirtual.Text = "Asset Tag"

$VMPanel.Controls.Add($AssetTagLabelVirtual)
$VmwareToolsTextBox.Font = New-Object System.Drawing.Font("Calibri",12,1,3,0)
$VmwareToolsTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,227,227,227)
$VmwareToolsTextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 136
$VmwareToolsTextBox.Location = $System_Drawing_Point
$VmwareToolsTextBox.Name = "VmwareToolsTextBox"
$VmwareToolsTextBox.ReadOnly = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 220
$VmwareToolsTextBox.Size = $System_Drawing_Size
$VmwareToolsTextBox.TabIndex = 5

foreach ($service in (gwmi -q "select * from Win32_service")){if ($service.pathname -match "vmtoolsd.exe"){$VMToolPath = $service.pathname}}
if ($VMToolPath -ne $null){
    $VMVersion = [system.diagnostics.fileversioninfo]::GetVersionInfo($VMToolPath.Substring(1,($VMToolPath.length -2))).productversion
    $VmwareToolsTextBox.Text = $VMVersion
    if ($VMVersion -eq "10.0.0 build-3000743"){
        $VmwareToolsTextBox.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
        $VmwareToolsTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,51,189,61)
    } else {
        $VmwareToolsTextBox.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
        $VmwareToolsTextBox.BackColor = [System.Drawing.Color]::FromArgb(255,246,255,101)
    }
} else {
    $VmwareToolsTextBox.Text = "VMwareTools NOT DETECTED"
    $VmwareToolsTextBox.ForeColor = [System.Drawing.Color]::White
    $VmwareToolsTextBox.BackColor = [System.Drawing.Color]::Red
}
$VMPanel.Controls.Add($VmwareToolsTextBox)

$VmwareToolsLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$VmwareToolsLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,0)
$VmwareToolsLabel.ForeColor = [System.Drawing.Color]::FromArgb(255,105,105,105)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 110
$VmwareToolsLabel.Location = $System_Drawing_Point
$VmwareToolsLabel.Name = "VmwareToolsLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 194
$VmwareToolsLabel.Size = $System_Drawing_Size
$VmwareToolsLabel.TabIndex = 4
$VmwareToolsLabel.Text = "VMware Tools Version"

$VMPanel.Controls.Add($VmwareToolsLabel)

$ClusterTextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 90
$ClusterTextBox.Location = $System_Drawing_Point
$ClusterTextBox.Name = "ClusterTextBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 100
$ClusterTextBox.Size = $System_Drawing_Size
$ClusterTextBox.TabIndex = 3
$ClusterTextBox.add_TextChanged($handler_ClusterTextBox_TextChanged)
$VMPanel.Controls.Add($ClusterTextBox)

$ClusterLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$ClusterLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,0)
$ClusterLabel.ForeColor = [System.Drawing.Color]::FromArgb(255,105,105,105)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 3
$System_Drawing_Point.Y = 72
$ClusterLabel.Location = $System_Drawing_Point
$ClusterLabel.Name = "ClusterLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 140
$ClusterLabel.Size = $System_Drawing_Size
$ClusterLabel.TabIndex = 2
$ClusterLabel.Text = "Cluster"

$VMPanel.Controls.Add($ClusterLabel)

$DataCenterTextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 48
$DataCenterTextBox.Location = $System_Drawing_Point
$DataCenterTextBox.Name = "DataCenterTextBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 100
$DataCenterTextBox.Size = $System_Drawing_Size
$DataCenterTextBox.TabIndex = 1




$VMPanel.Controls.Add($DataCenterTextBox)

$DataCenterLabel.BackColor = [System.Drawing.Color]::FromArgb(0,255,255,255)
$DataCenterLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$DataCenterLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,0)
$DataCenterLabel.ForeColor = [System.Drawing.Color]::FromArgb(255,105,105,105)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 3
$System_Drawing_Point.Y = 23
$DataCenterLabel.Location = $System_Drawing_Point
$DataCenterLabel.Name = "DataCenterLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 101
$DataCenterLabel.Size = $System_Drawing_Size
$DataCenterLabel.TabIndex = 0
$DataCenterLabel.Text = "DataCenter"

$VMPanel.Controls.Add($DataCenterLabel)



$PhysicalPanel.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 6
$PhysicalPanel.Location = $System_Drawing_Point
$PhysicalPanel.Name = "PhysicalPanel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 255
$System_Drawing_Size.Width = 407
$PhysicalPanel.Size = $System_Drawing_Size
$PhysicalPanel.TabIndex = 14

$ServerInfoInputTab.Controls.Add($PhysicalPanel)
$StateComboBox.DataBindings.DefaultDataSourceUpdateMode = 0
$StateComboBox.FormattingEnabled = $True
$StateComboBox.Items.Add("AK")|Out-Null
$StateComboBox.Items.Add("AL")|Out-Null
$StateComboBox.Items.Add("AZ")|Out-Null
$StateComboBox.Items.Add("AR")|Out-Null
$StateComboBox.Items.Add("CA")|Out-Null
$StateComboBox.Items.Add("CO")|Out-Null
$StateComboBox.Items.Add("CT")|Out-Null
$StateComboBox.Items.Add("DE")|Out-Null
$StateComboBox.Items.Add("FL")|Out-Null
$StateComboBox.Items.Add("GA")|Out-Null
$StateComboBox.Items.Add("HI")|Out-Null
$StateComboBox.Items.Add("ID")|Out-Null
$StateComboBox.Items.Add("IL")|Out-Null
$StateComboBox.Items.Add("IN")|Out-Null
$StateComboBox.Items.Add("IA")|Out-Null
$StateComboBox.Items.Add("KS")|Out-Null
$StateComboBox.Items.Add("KY")|Out-Null
$StateComboBox.Items.Add("LA")|Out-Null
$StateComboBox.Items.Add("ME")|Out-Null
$StateComboBox.Items.Add("MD")|Out-Null
$StateComboBox.Items.Add("MA")|Out-Null
$StateComboBox.Items.Add("MI")|Out-Null
$StateComboBox.Items.Add("MN")|Out-Null
$StateComboBox.Items.Add("MS")|Out-Null
$StateComboBox.Items.Add("MO")|Out-Null
$StateComboBox.Items.Add("MT")|Out-Null
$StateComboBox.Items.Add("NE")|Out-Null
$StateComboBox.Items.Add("NV")|Out-Null
$StateComboBox.Items.Add("NH")|Out-Null
$StateComboBox.Items.Add("NJ")|Out-Null
$StateComboBox.Items.Add("NM")|Out-Null
$StateComboBox.Items.Add("NY")|Out-Null
$StateComboBox.Items.Add("NC")|Out-Null
$StateComboBox.Items.Add("ND")|Out-Null
$StateComboBox.Items.Add("OH")|Out-Null
$StateComboBox.Items.Add("OK")|Out-Null
$StateComboBox.Items.Add("OR")|Out-Null
$StateComboBox.Items.Add("PA")|Out-Null
$StateComboBox.Items.Add("RI")|Out-Null
$StateComboBox.Items.Add("SC")|Out-Null
$StateComboBox.Items.Add("SD")|Out-Null
$StateComboBox.Items.Add("TN")|Out-Null
$StateComboBox.Items.Add("TX")|Out-Null
$StateComboBox.Items.Add("UT")|Out-Null
$StateComboBox.Items.Add("VT")|Out-Null
$StateComboBox.Items.Add("VA")|Out-Null
$StateComboBox.Items.Add("WA")|Out-Null
$StateComboBox.Items.Add("WV")|Out-Null
$StateComboBox.Items.Add("WI")|Out-Null
$StateComboBox.Items.Add("WY")|Out-Null
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 136
$StateComboBox.Location = $System_Drawing_Point
$StateComboBox.Name = "StateComboBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 121
$StateComboBox.Size = $System_Drawing_Size
$StateComboBox.TabIndex = 17

$PhysicalPanel.Controls.Add($StateComboBox)

$AssetTagTextBoxPhysical.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 237
$System_Drawing_Point.Y = 186
$AssetTagTextBoxPhysical.Location = $System_Drawing_Point
$AssetTagTextBoxPhysical.Name = "AssetTagTextBoxPhysical"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 100
$AssetTagTextBoxPhysical.Size = $System_Drawing_Size
$AssetTagTextBoxPhysical.TabIndex = 16

$PhysicalPanel.Controls.Add($AssetTagTextBoxPhysical)

$AssetTagLabelPhysical.DataBindings.DefaultDataSourceUpdateMode = 0
$AssetTagLabelPhysical.Font = New-Object System.Drawing.Font("Calibri",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 237
$System_Drawing_Point.Y = 162
$AssetTagLabelPhysical.Location = $System_Drawing_Point
$AssetTagLabelPhysical.Name = "AssetTagLabelPhysical"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$AssetTagLabelPhysical.Size = $System_Drawing_Size
$AssetTagLabelPhysical.TabIndex = 15
$AssetTagLabelPhysical.Text = "Asset Tag"

$PhysicalPanel.Controls.Add($AssetTagLabelPhysical)

$ShelfTextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 237
$System_Drawing_Point.Y = 135
$ShelfTextBox.Location = $System_Drawing_Point
$ShelfTextBox.Name = "ShelfTextBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 100
$ShelfTextBox.Size = $System_Drawing_Size
$ShelfTextBox.TabIndex = 14

$PhysicalPanel.Controls.Add($ShelfTextBox)

$ShelfLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$ShelfLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 237
$System_Drawing_Point.Y = 113
$ShelfLabel.Location = $System_Drawing_Point
$ShelfLabel.Name = "ShelfLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$ShelfLabel.Size = $System_Drawing_Size
$ShelfLabel.TabIndex = 13
$ShelfLabel.Text = "Shelf"

$PhysicalPanel.Controls.Add($ShelfLabel)

$RackTextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 237
$System_Drawing_Point.Y = 90
$RackTextBox.Location = $System_Drawing_Point
$RackTextBox.Name = "RackTextBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 100
$RackTextBox.Size = $System_Drawing_Size
$RackTextBox.TabIndex = 12

$PhysicalPanel.Controls.Add($RackTextBox)

$RackLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$RackLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 237
$System_Drawing_Point.Y = 71
$RackLabel.Location = $System_Drawing_Point
$RackLabel.Name = "RackLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$RackLabel.Size = $System_Drawing_Size
$RackLabel.TabIndex = 11
$RackLabel.Text = "Rack"

$PhysicalPanel.Controls.Add($RackLabel)

$FloorTextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 237
$System_Drawing_Point.Y = 48
$FloorTextBox.Location = $System_Drawing_Point
$FloorTextBox.Name = "FloorTextBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 100
$FloorTextBox.Size = $System_Drawing_Size
$FloorTextBox.TabIndex = 10

$PhysicalPanel.Controls.Add($FloorTextBox)

$FloorLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$FloorLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 237
$System_Drawing_Point.Y = 23
$FloorLabel.Location = $System_Drawing_Point
$FloorLabel.Name = "FloorLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$FloorLabel.Size = $System_Drawing_Size
$FloorLabel.TabIndex = 9
$FloorLabel.Text = "Floor"

$PhysicalPanel.Controls.Add($FloorLabel)

$StateLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$StateLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 3
$System_Drawing_Point.Y = 113
$StateLabel.Location = $System_Drawing_Point
$StateLabel.Name = "StateLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$StateLabel.Size = $System_Drawing_Size
$StateLabel.TabIndex = 4
$StateLabel.Text = "State"

$PhysicalPanel.Controls.Add($StateLabel)

$CityTextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 90
$CityTextBox.Location = $System_Drawing_Point
$CityTextBox.Name = "CityTextBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 182
$CityTextBox.Size = $System_Drawing_Size
$CityTextBox.TabIndex = 3

$PhysicalPanel.Controls.Add($CityTextBox)

$CityLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$CityLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 72
$CityLabel.Location = $System_Drawing_Point
$CityLabel.Name = "CityLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$CityLabel.Size = $System_Drawing_Size
$CityLabel.TabIndex = 2
$CityLabel.Text = "City"

$PhysicalPanel.Controls.Add($CityLabel)

$StreetLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$StreetLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 3
$System_Drawing_Point.Y = 23
$StreetLabel.Location = $System_Drawing_Point
$StreetLabel.Name = "StreetLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 122
$StreetLabel.Size = $System_Drawing_Size
$StreetLabel.TabIndex = 1
$StreetLabel.Text = "Street Address"
$StreetLabel.add_Click($handler_label8_Click)

$PhysicalPanel.Controls.Add($StreetLabel)

$StreetTextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 49
$StreetTextBox.Location = $System_Drawing_Point
$StreetTextBox.Name = "StreetTextBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 182
$StreetTextBox.Size = $System_Drawing_Size
$StreetTextBox.TabIndex = 0

$PhysicalPanel.Controls.Add($StreetTextBox)

$WarrentyExpirationTextBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 186
$WarrentyExpirationTextBox.Location = $System_Drawing_Point
$WarrentyExpirationTextBox.Name = "WarrentyExpirationTextBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 182
$WarrentyExpirationTextBox.Size = $System_Drawing_Size
$WarrentyExpirationTextBox.TabIndex = 0

$PhysicalPanel.Controls.Add($WarrentyExpirationTextBox)

$WarrentyExpirationLabel.DataBindings.DefaultDataSourceUpdateMode = 0
$WarrentyExpirationLabel.Font = New-Object System.Drawing.Font("Calibri",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 163
$WarrentyExpirationLabel.Location = $System_Drawing_Point
$WarrentyExpirationLabel.Name = "WarrentyExpirationLabel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 150
$WarrentyExpirationLabel.Size = $System_Drawing_Size
$WarrentyExpirationLabel.TabIndex = 4
$WarrentyExpirationLabel.Text = "Warrenty Expiration"

$PhysicalPanel.Controls.Add($WarrentyExpirationLabel)


$ServerHistoryTab.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 27
$ServerHistoryTab.Location = $System_Drawing_Point
$ServerHistoryTab.Name = "ServerHistoryTab"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 331
$System_Drawing_Size.Width = 710
$ServerHistoryTab.Size = $System_Drawing_Size
$ServerHistoryTab.TabIndex = 2
$ServerHistoryTab.Text = "Server History"
$ServerHistoryTab.UseVisualStyleBackColor = $True

$TabContainer.Controls.Add($ServerHistoryTab)
$vScrollBar1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 689
$System_Drawing_Point.Y = 3
$vScrollBar1.Location = $System_Drawing_Point
$vScrollBar1.Name = "vScrollBar1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 333
$System_Drawing_Size.Width = 21
$vScrollBar1.Size = $System_Drawing_Size
$vScrollBar1.TabIndex = 1

$ServerHistoryTab.Controls.Add($vScrollBar1)

$dataGridView1.BackgroundColor = [System.Drawing.Color]::FromArgb(255,176,224,230)
$dataGridView1.BorderStyle = 0
$dataGridView1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 3
$System_Drawing_Point.Y = 3
$dataGridView1.Location = $System_Drawing_Point
$dataGridView1.Name = "dataGridView1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 472
$System_Drawing_Size.Width = 901
$dataGridView1.Size = $System_Drawing_Size
$dataGridView1.TabIndex = 0
$dataGridView1.ColumnCount = 3
$dataGridView1.Columns[0].Name = "Name"
$dataGridView1.Columns[1].Name = "Change Performed"
$dataGridView1.Columns[2].Name = "Date"

$ServerHistoryTab.Controls.Add($dataGridView1)

###                                ###
# Ingest Server History and settings #
###                                ###

if (Test-Path HKLM:\SOFTWARE\CSC-Sick\History){ 
$PrimaryFunctionTextBox.Text = Get-ItemProperty -Path $RegRoot | select -ExpandProperty PrimaryFunction
$ServerFunctionComboBox.Text = Get-ItemProperty -Path $RegRoot | select -ExpandProperty ServerFunction
$CostCenterTextBox.Text = Get-ItemProperty -Path $RegRoot | select -ExpandProperty CostCenter
$SanAttachedComboBox.Text = Get-ItemProperty -Path $RegRoot | select -ExpandProperty SanAttached
$BuilddatetimeTextBox.Text = Get-ItemProperty -Path $RegRoot | select -ExpandProperty BuildDate
$BuildAdminTextBox.Text = Get-ItemProperty -Path $RegRoot | select -ExpandProperty BuildAdmin
$script:AssetTagTextBoxVirtual.Text = Get-ItemProperty -Path $RegRoot | select -ExpandProperty AssetTag
$AssetTagTextBoxPhysical.Text = Get-ItemProperty -Path $RegRoot | select -ExpandProperty AssetTag
    
    if ($isThisVirtual){
       $DataCenterTextBox.Text = Get-ItemProperty -Path $RegRoot | select -ExpandProperty DataCenter
       $ClusterTextBox.Text = Get-ItemProperty -Path $RegRoot | select -ExpandProperty Cluster
       $script:AssetTagTextBoxVirtual.Text = Get-ItemProperty -Path $RegRoot | select -ExpandProperty AssetTag
    } else {
        $StreetTextBox.Text =  Get-ItemProperty -Path $RegRoot | select -ExpandProperty StreetAddress
        $CityTextBox.Text = Get-ItemProperty -Path $RegRoot | select -ExpandProperty City
        $StateComboBox.Text = Get-ItemProperty -Path $RegRoot | select -ExpandProperty State
        $FloorTextBox.Text = Get-ItemProperty -Path $RegRoot | select -ExpandProperty Floorr
        $RackTextBox.Text = Get-ItemProperty -Path $RegRoot | select -ExpandProperty Rack
        $ShelfTextBox.Text = Get-ItemProperty -Path $RegRoot | select -ExpandProperty Shelf
        $AssetTagTextBoxPhysical = Get-ItemProperty -Path $RegRoot | select -ExpandProperty AssetTag
    }
} else {
    New-Item ($RegRoot + "History") -ItemType Directory -force
    Set-ItemProperty -Path $RegRoot -Name AssetTag -Value ""
    Set-ItemProperty -Path $RegRoot -Name BuildAdmin -Value ""
    Set-ItemProperty -Path $RegRoot -Name BuildDate -Value ""
    Set-ItemProperty -Path $RegRoot -Name City -Value ""
    Set-ItemProperty -Path $RegRoot -Name Cluster -Value ""
    Set-ItemProperty -Path $RegRoot -Name CostCenter -Value ""
    Set-ItemProperty -Path $RegRoot -Name DataCenter -Value ""
    Set-ItemProperty -Path $RegRoot -Name Floor -Value ""
    Set-ItemProperty -Path $RegRoot -Name LanDeskVersion -Value ""
    Set-ItemProperty -Path $RegRoot -Name PrimaryFunction -Value "" -Type MultiString
    Set-ItemProperty -Path $RegRoot -Name Rack -Value ""
    Set-ItemProperty -Path $RegRoot -Name RSAVersion -Value ""
    Set-ItemProperty -Path $RegRoot -Name SanAttached -Value ""
    Set-ItemProperty -Path $RegRoot -Name SEPVersion -Value ""
    Set-ItemProperty -Path $RegRoot -Name ServerActivation -Value ""
    Set-ItemProperty -Path $RegRoot -Name ServerFunction -Value ""
    Set-ItemProperty -Path $RegRoot -Name Shelf -Value ""
    Set-ItemProperty -Path $RegRoot -Name SIEM/ALEVersion -Value ""
    Set-ItemProperty -Path $RegRoot -Name State -Value ""
    Set-ItemProperty -Path $RegRoot -Name StreetAddress -Value ""
    Set-ItemProperty -Path $RegRoot -Name VMWareToolsVersion -Value ""
    Set-ItemProperty -Path $RegRoot -Name WUInstall -Value ""
    Set-ItemProperty -Path $RegRoot -Name WarrantyExpiration -Value ""
}

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null
} #End Function

#Call the Function
GenerateForm
